### PR TITLE
add spanish localization strings

### PR DESCRIPTION
**Pull request by ogomez92**
This file are the Spanish localization strings.

Note. I didn't specify a language locale (es instead of es-es). I would like it to work with Latin American Spanish, as well, not just es-es.

### CODE REVIEW

**Comment by Aurelius7309** [comment]
Thanks for the translation! Balatro includes two different Spanish locales, `es_ES` as well as `es_419` for Latin American Spanish. Will it be fine for me to duplicate the file in order to use it for both?

**Comment by ogomez92** [comment]
Hi, yes, that's fine!

**Comment by Aurelius7309** [comment]
Hey, there's been a few more localization strings added concerning settings and challenge mode. This should be good to go if you can add these in. Thanks :)

**Comment by ogomez92** [comment]
I had to open a new pr, the branch didn't seem to be active anymore.

**Pull request closed without merging**
